### ISSUE TITLE
Allow multiple hosts for the dashboard

### ISSUE THREAD

**Issue by dfishburn** [nickytd/kubernetes-logging-helm#11]
Currently, we have access to only 1 host name:
`opensearch_dashboards.ingress.host`

This means, when I create a DNS entry under my own domain, I must wait until the `ingress` is created, and depending on which hyperscaler I am on, either use an AWS load balancer CNAME or on Azure, use the IP address assigned.

I had noticed with ELK, I could create multiple hosts, and was able to use a DNS name for the cluster.  So this name would always resolve.

It looks something like this in values.yaml:
```
opensearch_dashboards:
  ingress:
    enabled: true 
    hosts: 
      - logs-os.sandbox.my.domain
      - kibana.ingress.sandboxbsh-a.iotdevk8s.shoot.canary.k8s-hana.some.com
```
This will generate the following ingress:
```
  - host: logs-os.sandbox.my.domain
    http:
      paths:
      - backend:
          service:
            name: ofd-opensearch-dashboards
            port:
              number: 5601
        path: /
        pathType: Prefix
  - host: dashboards.ingress.sandboxbsh-a.iotdevk8s.shoot.canary.some.com
    http:
      paths:
      - backend:
          service:
            name: ofd-opensearch-dashboards
            port:
              number: 5601
        path: /
        pathType: Prefix
```

Which means, when I create the DNS entry:
`logs-os.sandbox.my.domain`
I can point it at the automatically exposed hostname:
`kibana.ingress.sandboxbsh-a.iotdevk8s.shoot.canary.k8s-hana.some.com`

And then don't have to mess around with my DNS entries after the fact.

PR is completed and tested.

It allows for backwards compatibility if you continue to use:
```
opensearch_dashboards:
  ingress:
    enabled: true 
    host: 
```
But it will also check for:
```
opensearch_dashboards:
  ingress:
    enabled: true 
    hosts: 
```
