### ISSUE TITLE
Question - allowlists

### ISSUE THREAD

**Issue by dfishburn** [nickytd/kubernetes-logging-helm#19]
We have a requirement to lock down the URL to various internal offices, rather than access from the entire internet.

I had a quick look through the values.yml but didn't see any provision for specifying an allowlist for the dashboard.

Just wondering if this is possible today?

**Comment by dfishburn** [comment]
I have been able to do this now using Istio.
So for the dashboards, I turn off the nginx ingress (which is by default `enabled=false`)
Then manually setup the Istio gear.

Create a TLS domain secret in `istio-ingress`
```
kubectl create secret tls domain-cert-secret --cert=sandbox.my.domain.pub --key=sandbox.my.domain.key -n istio-ingress
```
Create an Istio Gateway
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: ofd
    meta.helm.sh/release-namespace: os-logging
  labels:
    app.kubernetes.io/instance: ofd
    app.kubernetes.io/name: kubernetes-logging
    type: opensearch-dashboards
  name: opensearch-gateway
  namespace: istio-ingress
spec:
  selector:
    app: istio-ingress
  servers:
  - hosts:
    - logs-c.sandbox.my.domain
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: domain-cert-secret
      mode: SIMPLE
```
Create a VirtualService
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  annotations:
    meta.helm.sh/release-name: ofd
    meta.helm.sh/release-namespace: os-logging
  labels:
    app.kubernetes.io/instance: ofd
    app.kubernetes.io/name: kubernetes-logging
    type: opensearch-dashboards
  name: opensearch
  namespace: istio-ingress
spec:
  exportTo:
  - istio-ingress
  gateways:
  - opensearch-gateway
  hosts:
  - logs-c.sandbox.my.domain
  http:
  - name: default-route-opensearch
    route:
    - destination:
        host: ofd-opensearch-dashboards.os-logging.svc.cluster.local
        port:
          number: 5601
```
For the AllowList, you need to modify the Istio Service:
```
kubectl -n istio-ingress patch service istio-ingress --type='json' -p='[{"op": "add", "path": "/metadata/annotations/service.beta.kubernetes.io~1load-balancer-source-ranges", "value":"10.10.128.200/32, 10.10.128.201/32, 10.10.128.202/32, 10.20.0.0/17"}]'
```
